title: Tushar Lathiya Portfolio
description: Magento Developer & ERP Integration Specialist
theme: jekyll-theme-minimal
show_downloads: false

# Navigation links
nav:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Resume
    url: /resume
  - title: Contact
    url: /contact
